### ISSUE TITLE
Student Side Button Functionality - Rerun Autograder/Download Submission

### ISSUE THREAD

**Issue by kenlu66** [kiat/codeAssist#104]
Rerun Autograder:
When clicked, the autograder should rerun the most recent submission.
Students should receive feedback indicating that the autograder has been re-run.
If the autograder encounters any issues, an error message should be displayed explaining the reason (e.g., "Autograder unavailable" or "Invalid submission").

**Comment by kenlu66** [comment]
Currently, the "Rerun Autograder" and "Download Submission" buttons on the student side are non-functional. These buttons do not trigger any actions or responses when clicked.

**Expected Behavior:**
Rerun Autograder:
When clicked, the autograder should rerun the most recent submission.
Students should receive feedback indicating that the autograder has been re-run.
If the autograder encounters any issues, an error message should be displayed explaining the reason (e.g., "Autograder unavailable" or "Invalid submission").

Download Submission:
When clicked, the student's latest submission should be downloaded as a file (e.g., a .zip containing the submitted documents).
If no submission exists, the button should display a message like "No submission available to download."

**Comment by kenlu66** [comment]
Download Submission is fully functional.

**Comment by kiat** [comment]
Thanks!
