### ISSUE TITLE
Course name doesn't show up for student

### ISSUE THREAD

**Issue by jamisen-ma** [kiat/codeAssist#21]
<img width="333" alt="Screen Shot 2023-02-07 at 3 06 41 PM" src="https://user-images.githubusercontent.com/100271213/217365614-11f86a97-866e-4e80-a6b4-abf41f84abf1.png">

**Comment by DannyBanany123** [comment]
Issue was in getStudentCourses in index.js in frontend/src/pages. That method calls the get_student_enrollments() service in app.py, and it only returns rows from the enrollments table of the db, which do not contain any information about the course names. To resolve the issue, I used the returned course_id's from the enrollments table to query into the courses table. The new retrun value is a JSON of the enrolled courses of a specific student from the courses table.
