### ISSUE TITLE
Course settings functionality

### ISSUE THREAD

**Issue by rurushah** [kiat/codeAssist#28]
Update, deactivate, reactivate buttons on frontend have no functionality. Courses cannot be deleted because "there are assignments" even when there are no assignments created

**Comment by rurushah** [comment]
There is no connection between creating a course and its actual information (name, semester, year, etc.)

**Comment by kiat** [comment]
First look which tables we have for the data.
- implement in backend and then in frontend

**Comment by pth1209** [comment]
I am pretty sure these issues have been resolved, especially with the delete course, update course, and the course information display.
