### ISSUE TITLE
Create repository based project for Code Assist

### ISSUE THREAD

**Issue by woodruffr4** [kiat/codeAssist#3]
It would be nice to have a Kanban board associated with this project so that we can track tasks with To Do, In Progress, and Done. In order to do this, we will need to attach a repository-based project to this repo. I don't think I have the right permissions to do this from my account. 

Information on creating a project can be found here: https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards

Step by step for creating a project: https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/creating-a-project-board#creating-a-repository-classic-project

*Note*: when selecting a template, please choose "Basic Kanban"

**Comment by kiat** [comment]
Thanks!
