### ISSUE TITLE
Course information not updated correctly

### ISSUE THREAD

**Issue by pranavsridhar** [kiat/codeAssist#30]
Regardless of the name selected for a new course, the course name is not reflected correctly in the upper left corner of the dashboard page for the course. Leftmost corner always displays "C S N313E \nSu22 - ELEMENTS OF SOFTWARE DESIGN-WB(86439)"; uppermost corner always displays "CS 313E \nSummer 2022". **From instructor side**

**Comment by pth1209** [comment]
In index.js in /frontend/instructor/dashboard/index.js, it is hardcoded

 PageHeader title='CS 313E' subTitle='Summer 2022'

**Comment by pranavsridhar** [comment]
Yup, I've replaced that part with codeInfo.name on my end, haven't pushed yet. Trying to troubleshoot the semester/year part, which I think might have something to do with course settings. Also, the title affects the uppermost text, but the leftmost text (CS N313E ...) is the same, so I'm also trying to pin that down

**Comment by pth1209** [comment]
Oh my bad I already pushed and changed it to courseInfo.name just like you did. I'm also tryna figure our semester/year/entryCode part

**Comment by pranavsridhar** [comment]
no problem haha, thanks for the help. Let me know if you find anything else/make any new changes. Also, did you push to the main branch?

**Comment by pth1209** [comment]
I changed the database for the courses table where I added columns for semester, year, and entryCode to access it easier.

**Comment by pranavsridhar** [comment]
resolved
