### ISSUE TITLE
Add Students or Staff button on the enrollment page doesnt work

### ISSUE THREAD

**Issue by Kyildirim24** [kiat/codeAssist#33]

**Comment by pth1209** [comment]
You have to add them using the id in the student table in the database, which is formatted in uuid. However, when adding the student, the console does log a warning on "Each child in a list should have a unique "key" prop."

**Comment by Kyildirim24** [comment]
yeah the thing used here shouldnt be the uuid. the uuid is supposed to be only on the server and never available to any of the users. so I am adding an EID prompt when signing up so that we can actually have students own IDs to use for adding students instead of having to use uuid which will realistically never be known to the users. I am currently trying to fix this issue

**Comment by Kyildirim24** [comment]
solved in commit d624e32

The uuid is not used to add students anymore. Students are now added with EIDs instead. The AddUserModal is also changed to only ask for the EID now and the enrollments page correctly show enrolled students' names and emails.
